apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cluster-vault-secret-store
  namespace: payments-ns-with-rq
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-secret
  namespace: payments-ns-with-rq
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: cluster-vault-secret-store
    kind: SecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: payments/db
        property: username
    - secretKey: password
      remoteRef:
        key: payments/db
        property: password
