# name: Terraform Deployment

# on:
#   push:
#     branches: ["main", "master"]
#   pull_request:
#     branches: ["main", "master"]

# permissions:
#   id-token: write
#   contents: read

# env:
#   ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./iac

#     steps:
#       - uses: actions/checkout@v4

#       - name: Fetch Keys from Vault
#         uses: hashicorp/vault-action@v3
#         with:
#           url: http://3.109.155.146:8200
#           role: gh-actions-role
#           method: jwt
#           secrets: aws/creds/terraform-role access_key | AWS_ACCESS_KEY_ID

#       - uses: hashicorp/setup-terraform@v3
#       - run: terraform init
#       - run: terraform plan